### ISSUE TITLE
Storybook

### ISSUE THREAD

**Issue by andrew-secret** [OpenSourceRaidGuild/website#13]
# Implement Storybook in the Frontend

- [x]  I would like to work on this feature!

## What is Storybook
Storybook is an open source tool for developing UI components in isolation for React, Vue, Angular, and of course Svelte 😉
[for further information read here](https://storybook.js.org/docs/svelte/get-started/introduction).

## Why we should implement it?
We can structure our work more and benefit from the encapsulation of UI components (e.g. by having fewer merge conflicts). The other point is that we get a better overview of our application because you can reflect each state of the UI component within a story. It's also easier to do some QA and testing since it's  encapsulated from the application

## Goal

- setup Storybook (install npm package, setup `storybook/main.js` ... )
- write stories for the components
- (consider useful addons for storybook) only if it's a real benefit for us otherwise we just keep it simple
- add storybook to our documentation

One approach would be to wrap all components into its own folder and add stories (later on we can also write unit tests within that folder)

Folder structure:
```
├── ...
├── Card/             
│   ├──  Card.svelte 
│   ├──  Card.stories.ts
│   └──  Card.spec.ts (future stuff)
└── ...

```

## Problems we might run into
Make it work together with Typescript. I remember that it was always a bit of a struggle. But here's a link to an [issue that looks promising](https://github.com/storybookjs/storybook/issues/12754) to me 🤞

**Comment by nobrayner** [comment]
I'd be more interested to see how Storybook plays with Snowpack than anything... I think the TS should not be too bad - I have already gotten it working with Jest!

**Comment by andrew-secret** [comment]
> I'd be more interested to see how Storybook plays with Snowpack than anything... I think the TS should not be too bad - I have already gotten it working with Jest!

Good hint 🙏 I'll report to you in this issue regarding snowpack ❄️ ((I hope it's not PITA 😅))

**Comment by andrew-secret** [comment]
So far we can see the `LoadingSpinner` component in storybook 
![image](https://user-images.githubusercontent.com/13103896/105104918-75fb9580-5ab3-11eb-9108-9c851ec919e5.png)

TIL Storybook is working out of the box with Typescript 🤯

**Comment by tigerabrodi** [comment]
@andrew-secret Seems nice! Kudos :fire:

**Comment by nobrayner** [comment]
@andrew-secret Is there ready for a PR yet? I'm really excited to start playing around with it :stuck_out_tongue_closed_eyes:

**Comment by tigerabrodi** [comment]
@andrew-secret Our website is now in ReactJS, this has to be re-implemented I believe :+1:.

**Comment by pbteja1998** [comment]
I have worked with storybook before. I can quickly help set up the storybook. Please let me know if this issue is up for grabs.

**Comment by tigerabrodi** [comment]
Depends on @andrew-secret, if he does not respond in a few days, imo someone else can implement StoryBook, it should not take long as well tbh.

**Comment by pbteja1998** [comment]
@tigerabrodi I just opened a PR. Feel free to ignore it if @andrew-secret raises a PR.

**Comment by andrew-secret** [comment]
If you already have a pr it's totally fine but I worked on that issue for days and I couldn't figure out how to resolve the typescript warning..

**Comment by andrew-secret** [comment]
@nobrayner yeah I have something to show but it seems someone already submitted a pr 🙃
