### ISSUE TITLE
Stat Compactor

### ISSUE THREAD

**Issue by nobrayner** [OpenSourceRaidGuild/website#18]
Currently I am manually running some code to pull the stats from GitHub. It doesn't work perfectly, the rules need tweaking, and it needs to be automated.

This issue is just to document that it is being done, and the process to achieve it.

**Comment by iamstiil** [comment]
For reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events

**Comment by nobrayner** [comment]
This is now falling under Guild Scriviner - but will be tracked here

**Comment by nobrayner** [comment]
This has been completed - at least the basic working version
