### ISSUE TITLE
Homepage Wireframe/Mockup/Implementation

### ISSUE THREAD

**Issue by nobrayner** [OpenSourceRaidGuild/website#19]
Issue for Wireframing the homepage

**Comment by ziedtouibi** [comment]
I think a header is enough for the moment, we don't need a landing page, something like this
[https://www.figma.com/proto/oOFsQ2ecdyYjnK91yOKPDR/Raid-Guild-Site-Planning?node-id=91%3A269&scaling=min-zoom](https://www.figma.com/proto/oOFsQ2ecdyYjnK91yOKPDR/Raid-Guild-Site-Planning?node-id=91%3A269&scaling=min-zoom)

**Comment by nobrayner** [comment]
@ziedtouibi I am happy with this as an example - can you create an issue to have this built with any assets required attached?

**Comment by MohitPopli** [comment]
Is this picked up by anyone? I cannot see any issue created for it with the assets required. I would like to jump start on it.

**Comment by nobrayner** [comment]
@MohitPopli if you create a figma account, then the following URL should let you poke around the designs, and export assets etc...

Use them as placeholder until @ziedtouibi can get back to us :smiley: 

https://www.figma.com/file/oOFsQ2ecdyYjnK91yOKPDR/Raid-Guild-Site-Planning?node-id=36%3A0
