### ISSUE TITLE
How to handle accessibility.

### ISSUE THREAD

**Issue by YPAzevedo** [OpenSourceRaidGuild/website#23]
What approach re we using to deal with accessibility in the application? Any toolkits or write it all ourselves?

**Comment by YPAzevedo** [comment]
https://reakit.io/ this could be useful

**Comment by merodiro** [comment]
https://reach.tech/ is another option that can be useful. their styling is optional so we can override it or remove it easily

**Comment by codyarose** [comment]
I've heard Reach recommended by Kent, though I haven't used it much. I haven't heard of Reakit, but it seems to be essentially the same thing as Reach. I think building a list of pros/cons of each would be helpful

**Comment by tigerabrodi** [comment]
We can use StoryBook's addon: https://medium.com/@kruthiv/storybook-accessibility-9af2174bd93a

When we implement the e2e tests with Cypress, we can audit for a11y https://timdeschryver.dev/blog/setting-up-cypress-with-axe-for-accessibility

We can also audit for a11y in our integration tests https://medium.com/@eauditory3/accessibility-testing-in-react-with-jest-axe-e08c2a3f3289 :+1:.

**Comment by andrew-secret** [comment]
You could also try using this storybook addon 
https://www.npmjs.com/package/@storybook/addon-a11y

And can't we configure eslint.. I remember that I worked on some projects that we're configured like.
https://www.npmjs.com/package/eslint-plugin-jsx-a11y

**Comment by datner** [comment]
if we rely on an addon for an addon we _will_ encounter a coverage problem. 
I think that the correct approach will be to use a linter like [axe](https://axe-linter.deque.com/), so I agree with @andrew-secret  about that. If we want another way to enforce our a11y theres always the [`@axe-core`](https://www.npmjs.com/package/@axe-core/react) project. But nothing will beat just trying to keep a11y in the back of your head. Also prepare yourselves gentlemen, a11y is a lot of noise

**Comment by tigerabrodi** [comment]
As I have mentioned here as well https://github.com/OpenSourceRaidGuild/website/issues/23#issuecomment-766305488, aXe have their own Chrome extension, scanning each page and tackling the violations should not be hard :slightly_smiling_face:.

And if we do encounter serious a11y problems we can not solve, we can always ask people around for help. :100: 

A11y should not be trouble :clap:

**Comment by datner** [comment]
using an aXe chrome extension ensures that only core members who care about a11y will do a11y, since it requires the dev to install an outside tool unrelated to the project. It might be a tough sell..
I think we should add a11y to the toolchain if we want it to be takes seriously

**Comment by tigerabrodi** [comment]
@datner jest-axe and cypress-axe as mentioned in the comment as well :metal: 

We can make sure no PR goes through if cypress-axe throws any violations :3

**Comment by datner** [comment]
@tigerabrodi 
Won't this cause frustrations in development? Discovering your axe violations only after you committed code? Also if we add it to a linter it will fall in the pre-commit stage because of husky invoking `lint-staged`, meaning we won't need to run tests to discover what we lack. These can be used _as well_, but the closer to the dev side of the dev feedback cycle you get, the better the DX will be

**Comment by tigerabrodi** [comment]
@datner I agree there, guess we will have to find some sort of balance.

**Comment by datner** [comment]
we just have to make sure that which-ever methods we choose, they are compatible
