### ISSUE TITLE
💅🏻 How to handle styling.

### ISSUE THREAD

**Issue by YPAzevedo** [OpenSourceRaidGuild/website#24]
What are approach are we using for styling? Tailwind, Twind, Styled components, emotion... there's soo many options.

**Comment by AhmedEldessouki** [comment]
Css-in-js - Emotion =)

**Comment by YPAzevedo** [comment]
I think tailwind is a good approach and theres tailwind in js with twind
https://github.com/tw-in-js/twind

**Comment by merodiro** [comment]
I think either emotion with their [Object Style](https://emotion.sh/docs/object-styles#examples) syntax or tailwind/twind
both options don't require naming and make it easier to not have unused CSS in the code or class names names like "wrapper"

**Comment by codyarose** [comment]
Hopefully this doesn't become a divisive topic.
I think we should use emotion with a design system based on CSS custom properties. I'm not a fan of tailwind; I think it clutters the html and I don't really see much benefit in using it other than it's hot right now.

With emotion, I'm a fan of using the `styled.div` syntax because it's closer to native CSS, but I'm open to hearing how the object style syntax might be better.

**Comment by AhmedEldessouki** [comment]
> 
> 
> I think we should use emotion with a design system based on CSS custom properties. I'm not a fan of tailwind; I think it clutters the html and I don't really see much benefit in using it other than it's hot right now.
> 
> With emotion, I'm a fan of using the `styled.div` syntax because it's closer to native CSS, but I'm open to hearing how the object style syntax might be better.

As far as I know, both emotion/style and emotion/(core/react) are the same expect that with styled you create an HTML element with the css. on the other side, we add the css to the HTML tag using the css attribute (css can take css`` => for css string syntax  or an object for the style object syntax . =)
I hope this helps ^_^

**Comment by codyarose** [comment]
> As far as I know, both emotion/style and emotion/(core/react) are the same expect that with styled you create an HTML element with the css. on the other side, we add the css to the HTML tag using the css attribute (css can take css`` => for css string syntax or an object for the style object syntax . =)
> I hope this helps ^_^

So is it a purely stylistic choice? I've used the template strings syntax because it separates the styles from the html and, which I find far easier to read than having them inline like this:
```tsx
<div
    css={{
      color: 'darkorchid',
      '@media(min-width: 420px)': {
        color: 'orange'
      }
    }}
  >
    This is orange on a big screen and darkorchid on a small
    screen.
  </div>
```
The css props with template strings like this:
```tsx
const paragraph = css`
  color: turquoise;
`
render(
  <p css={paragraph}>
    Some text.
  </p>
)
```
is closer to how I would approach it; both the jsx and css are easier to read.


However, with the `styled.div` syntax you get the advantage of semantic naming, making it easy to read and understand what the component is actually for, you can easily export those components to reuse elsewhere, and it's written like native css
```tsx
const Card = styled.div`
  padding: 1rem;
`
const Description = styled.p`
  color: purple;
`

render(
  <Card>
    <Description>This is the description.</Description>
  </Card>
)
```

**Comment by YPAzevedo** [comment]
I'm good with emotion and the styled components approach ⬆️

**Comment by merodiro** [comment]
Naming everything is a double-edged sword. it's useful for reusable components but gets annoying for a one-off component that isn't going to be reusable

**Comment by nobrayner** [comment]
@codyarose @merodiro is it possible to combine both methods?

If it is reusable, use styled, otherwise, just use the object syntax???

**Comment by YPAzevedo** [comment]
Not everything that needs styling needs to be named too, we can use context styling:
```js
const Article = styled.article`
  // Aticle specific styling
  & > p + p {
    margin-bottom: 10px
  }
`

render(
  <Article>
    <p>(...)</p>
    <p>(...)</p>
    <p>(...)</p>
  </Article>
)
```

**Comment by YPAzevedo** [comment]
> @codyarose @merodiro is it possible to combine both methods?
> 
> If it is reusable, use styled, otherwise, just use the object syntax???

I don't really like the idea of mixing styling syntax 🤔

**Comment by codyarose** [comment]
Agreed @YPAzevedo 
A mixture of both could be used, but we should probably stick to one syntax. Naming elements can be annoying, but it gets the benefit of semantic intention, which helps other devs and your future self understand the structure. Taking advantage of nesting would cover most cases where there's not much value added by giving the element it's own name.

**Comment by YPAzevedo** [comment]
Ok, so we are moving with emotion and styled components approach? How should we reach a decision?

**Comment by nobrayner** [comment]
@YPAzevedo the people that have commented so far have come to a consensus - maybe you can work with Cody to get this started? :smile:

**Comment by YPAzevedo** [comment]
Making a PR to add the packages now.

**Comment by codyarose** [comment]
Okay, cool. I think for now we should just get emotion installed and ready to use. Not much styling has been done so far, so I'm not really worried about how they're styled right now. Once we get a design system going we can make PRs to refactor those

**Comment by YPAzevedo** [comment]
https://github.com/OpenSourceRaidGuild/website/pull/32
