### ISSUE TITLE
Create design system

### ISSUE THREAD

**Issue by codyarose** [OpenSourceRaidGuild/website#33]
I'd like to try a css custom properties based design system. 
Color palette, spacing, header sizes, and base element styles need to be decided on

**Comment by tigerabrodi** [comment]
@codyarose I personally think for colors and fonts this would be great. Otherwise for spacing, sizes, etc. I think we can go with such styles in the different styled components created with `emotion`. :+1:

**Comment by emma-r-slight** [comment]
> I'd like to try a css custom properties based design system.
> Color palette, spacing, header sizes, and base element styles need to be decided on

By Base element styles you mean create a box component, a form component -label and input with correct spacing.. a title component etc?

**Comment by codyarose** [comment]
> > I'd like to try a css custom properties based design system.
> > Color palette, spacing, header sizes, and base element styles need to be decided on
> 
> By Base element styles you mean create the styles for a box component, a form component -label and input with correct spacing.. a title component etc?

I was referring to the base elements like h1-6,p , and inputs. So basically a good normalize or reset with smart defaults so everything is starting from the same point across all browsers.

**Comment by nobrayner** [comment]
@codyarose following on from @emma-r-slight 's comment in Discord - are you thinking something along the lines of what https://every-layout.dev/rudiments/global-and-local-styling/ suggests?

**Comment by codyarose** [comment]
@nobrayner Yeah, I guess something along the lines of that, minus the xml "stack-l" part
