### ISSUE TITLE
prettier should be included in eslint config in `yarn lint`

### ISSUE THREAD

**Issue by JacobMGEvans** [OpenSourceRaidGuild/website#54]
prettier should be included in eslint config in `yarn lint`, no need to repeat on those files, only on `json|yml|yaml|css`, no?

_Originally posted by @Aprillion in https://github.com/OpenSourceRaidGuild/website/pull/53#discussion_r564540872_

**Comment by JacobMGEvans** [comment]
@AhmedEldessouki

**Comment by Aprillion** [comment]
No time to do right now, I will assign it back to me if noone will get to it by the time I have time 😂😂

**Comment by JacobMGEvans** [comment]
> No time to do right now, I will assign this issue back to me if no one will close it by the time I have time 😂😂

More for keeping you apprised since you had mentioned it but I realize it @ you anyway lol

**Comment by AhmedEldessouki** [comment]
on it =)

**Comment by merodiro** [comment]
prettier is already included in eslint config (`plugin:prettier/recommended`)
