### ISSUE TITLE
Create navbar component with links to home page, raids

### ISSUE THREAD

**Issue by codyarose** [OpenSourceRaidGuild/website#76]

**Comment by YPAzevedo** [comment]
Do we have the design for this?

**Comment by codyarose** [comment]
@YPAzevedo No, not yet. We just need something basic that fits with what currently exists so we have some way of navigating between screens

**Comment by emma-r-slight** [comment]
are we talking a basic header navbar component? or a basic link component to be used where ever?

**Comment by YPAzevedo** [comment]
The basic link component is the one from react-router no? just need to implement that on the application on a simple header, hopefully i can have some time to take this one today

**Comment by codyarose** [comment]
> are we talking a basic header navbar component? or a basic link component to be used where ever?

A header navbar component. I should've titled it that way :sweat_smile:
